### ISSUE TITLE
Filter products in shop by date and location

### ISSUE THREAD

**Issue by ScyDev** [ScyDev/reaction#18]
Products on the 3 main views `productList`, `productGrid` and `productMap` need to be filtered by location and date. The publication needs to be extended to include date and location in the selector. Currently, products are filtered by tag, this **needs to keep working**. 

**Date:**
The products have a field `forSaleOnDate` which is added in package `reaction-p2p-marketplace-sell-date`. 
Date field needs to use a datepicker, as it currently is with package `reaction-search`.

**Location:**
The products location is the location of the address[0] in the sellers profile. This is resolved for example in package `reaction-p2p-marketplace-locations`. 
Location search field needs to accept numeric postal code (4 digits) or name of city. Resolve it via Google Maps and select products which are within a certain radius.

Does **not necessarily** need to be realized with package `reaction-search`, but if it works it's ok.

**Budget:**
Max. 8 hours for reactive product filtering by tag, date and location in combination.
Plus 2 hours for resolving the users address through Google Maps and saving to user.profile.latitude and user.profile.longitude.

**Comment by ScyDev** [comment]
https://github.com/reactioncommerce/reaction/issues/274

**Comment by ScyDev** [comment]
https://github.com/reactioncommerce/reaction/issues/105

Working on https://github.com/reactioncommerce/reaction-search to make it compatible with 0.12 and enhance it for date and location filters.

**Comment by ramusus** [comment]
You may take a look https://github.com/ramusus/reaction-filtration/ it supports simple search functionality. You can integrate with current dev version, using this PR https://github.com/reactioncommerce/reaction/pull/743

**Comment by ScyDev** [comment]
@ramusus Thanks! I merged the 6 commits from your pull request into my branch, added package ramusus:reaction-filtration and activated it in admin dashboard.

How do I make it show up on the page?

**Comment by ramusus** [comment]
@ScyDev thanks! try to apply this PR https://github.com/reactioncommerce/reaction/pull/743. I'm not sure it's uptodate now to the latest development or 0.12 version, but you can find in the code where the link, that triggers the filters sidebar

**Comment by ScyDev** [comment]
done.
