### ISSUE TITLE
Unknown package error

### ISSUE THREAD

**Issue by fisherman818** [ScyDev/reaction#29]
Hi ScyDev,

Thanks for the good work on the Marketplace for Reaction! 

Today I was about to try your work and found this:

> error: unknown package in top-level dependencies: scydev:snaxter-template

It looks that the package is not inside the folder yet. So are you in the process of packaging your codes? 

Thank you!

**Comment by ScyDev** [comment]
Hi!

Thanks for your interest and sorry for the confusion. 
That package `snaxter-template` is a private repo because it contains a custom template that we don't want to share. You can just remove that package from `.meteor/packages.js`.
The same applies to package `reaction-email-templates-custom`.

I will remove these two submodules from the project, to avoid further confusion.

**Comment by fisherman818** [comment]
Thank you for the explanation!

Can I know what is your next stage plan for this project? Are you going to wrap everything (public) as packages and merge them with the main Reaction? Or you will keep it as a separate fork like now?

**Comment by ScyDev** [comment]
Yes, I would very much like to move all the core hacks (which I had to do to meet the project deadline) into separate packages and make them compatible with the latest Reaction.

It's a lot of work. If you're using this fork for your project, it would be great if you'd be able to help with that effort.

**Comment by fisherman818** [comment]
@ScyDev Yes, there will be a lot of work. Hope I can contribute to your work! Currently it is my pure interest to work with Meteor. Believe this is definitely the future for app development. 

Trying to get your codes to run on local machine now. But somehow I think maybe some cores have been modified? Because I don't see the package: `reaction-email-templates-custom` inside the ./meteor/packages. But the error: `unknown package: scydev:reaction-email-templates-custom` keeps showing up.

`snaxter-template` has been removed. No more related errors.

**Comment by ScyDev** [comment]
So do I. Meteor rocks extremely hard :)

Yes, the core has been modified in a lot of places.

And I might have referenced `reaction-email-templates-custom` in the `package.js` file of another package. Most likely `reaction-core`. You best `grep` for it.

I'm sorry it's so messy, didn't really have the time yet to do cleanup work for other people to use it.

**Comment by ScyDev** [comment]
Removed the private packages on `development` branch.

**Comment by priezz** [comment]
Lukas, it seems you did not remove references to `reaction-email-templates-custom` and `snaxter-template` from `git submodule`:

```
» git ls-files --stage | grep 
160000 3c9bf6ee98bb34c772837dff8da1fc34520182b8 0   packages/meteor-bootstrap3-datetimepicker
160000 eefb9e53d6d219026ceb49ac7586be0f8b1e591f 0   packages/meteor-collection2
160000 f0ca42f2e3a949e1eacefa09f0a20f308e35e5cb 0   packages/meteor-collection2-core
160000 dad63d8fa6b08b5341c2188b8fe5abdbc18e9ed7 0   packages/reaction-braintree
160000 7c05d491e98b5d6a5a9cb912ebc384153526adb1 0   packages/reaction-email-templates-custom
160000 c4858f7b8a8c55f5d66f20ce8b4b357e9ee1a1ee 0   packages/reaction-search
160000 096006e19796549b02b6c148fbd9e3c584ad88d0 0   packages/snaxter-template
```

Just run to fix:

```
git rm packages/reaction-email-templates-custom packages/snaxter-template
```

**Comment by ScyDev** [comment]
I removed them from `.gitmodules` file and committed that: 214e33ad0df8f2a44172e95473c18b6d4df8e619

Shouldn't that be enough?

**Comment by priezz** [comment]
Unfortunately not. Above I have provided an output, which shows that `git` still "knows" about these submodules. Directories with 160000 mode still are in the project, this mode is exclusive for submodules, when `git` have such a directory, that has no source in the `.gitmodules`, it drops an error. So to remove the module you have to do both, remove it from `.gitmodules` and run `git rm module_directory`.

**Comment by ScyDev** [comment]
I see. Did that now. Thanks for the explanation.
